version: "3"

services:
  viewer_app_server:
    container_name: "viewer_app_server"
    depends_on: 
      - viewer_app_db
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=viewer_app_db
      - POSTGRES_PORT=5430
    ports:
      - "127.0.0.1:1357:1357"
    networks:
      - net

  viewer_app_db:
    container_name: "viewer_app_db"
    image: postgres:15.2
    volumes:
      - ../.postgres-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5430}:5430"
    networks:
      - net

networks:
  net:
