name: Run tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: |
          requirements.txt
    - name: Install and update Python dependencies (dev?)
      run: |
        python -m pip install --upgrade pip pytest
        python -m pip install -r requirements.txt
    - name: Just Print PR info for debugging.
      run: |
        python src/__main__.py info
